name: deploy
on:
  push:
    branches: [main, fastTesting]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTODEPLOY_TAG: develop
      AUTODEPLOY_URL: https://dfusion.auto.gnosisdev.com/services/dfusion-v2-cowdexsolver/rollout
      DOCKERHUB_PROJECT: cowdexsolver
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: docker/deploy.sh ${GITHUB_REF#refs/*/}
