name: deploy
on:
  push:
    branches: [main]
    tags: [v*]
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTODEPLOY_TAG: develop
      AUTODEPLOY_URL: ${{ secrets.AUTODEPLOY_URL }}
      AUTODEPLOY_TOKEN: ${{ secrets.AUTODEPLOY_TOKEN }}
      DOCKERHUB_PROJECT: cowdexsolver
      DOCKER_NAME: ${{ secrets.DOCKER_NAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - uses: actions/checkout@v2
      - run: docker/deploy.sh ${GITHUB_REF#refs/*/}
